name: "构建PagerMaid"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest-amd64
          build-args: |
            S6_ARCH=amd64

      - name: Build and push arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest-arm64-v8
          build-args: |
            S6_ARCH=aarch64

      - name: Create and push manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest \
            ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest-arm64-v8
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/pagermaid_modify:latest
